spring:
  application:
    name: gateway8710
  cloud:
    gateway:
      default-filter:
      routes:
        - id: user-server
          predicates:
            - Path=/java/**
          filters:
            - StripPrefix=1
          uri: lb://service-helloword
            #uri: "http://localhost:8708"
server:
  port: 8710
eureka:
  client:
    serviceUrl:
      #指向注册中心
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2